name: 🔨 Build Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        go-version: [1.21.x]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Test
        run: go test ./...
        working-directory: .

      - name: Build
        run: go run .
        working-directory: examples/

      - name: Install
        run: go install
        working-directory: cmd/alterx/

      - name: Race Condition Tests
        run: echo "www.scanme.sh" | go run -race .
        working-directory: cmd/alterx/
