name: 🙏🏻 Lint Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
    paths:
      - '**.go'
      - '**.mod'
jobs:
  lint:
    name: Lint Test
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: latest
          args: --timeout 5m
          working-directory: .